### ISSUE TITLE
Bump modmail version to v3.7.0

### ISSUE THREAD

**Issue by wrac4242** [JesseStorms/docker_modmailbot#4]
hey, there was a new modmail [release](https://github.com/Dragory/modmailbot/releases/tag/v3.7.0). This is one of the main ones I've seen pointed to for docker container support in the past, will this update come through?

**Comment by JesseStorms** [comment]
I'll check it out if I have time. The update slipped past me.
Thanks for the heads up though

**Comment by JesseStorms** [comment]
closed by 64b26f1, should be fine. 
`/readme.md` has been updated to reflect the bump as well.
